### ISSUE TITLE
Config is not compatible with eslint >= 2.0.0

### ISSUE THREAD

**Issue by Greenek** [AtomBuild/eslint-config-atom-build#2]
Following rules has been removed:
- `no-empty-label` is replaced by `no-labels` with `{"allowLoop": true, "allowSwitch": true}` option.
- `space-after-keywords` is replaced by `keyword-spacing`.
- `space-before-keywords` is replaced by `keyword-spacing`.
- `space-return-throw-case` is replaced by `keyword-spacing`.

[More details](http://eslint.org/docs/user-guide/migrating-to-2.0.0)

**Comment by noseglid** [comment]
Fixed with #1
